DELETE FROM ms_kubun;

INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (1, '001', '01', 'はじめて', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (2, '001', '02', 'リピート', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (3, '002', '01', '車', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (4, '002', '02', 'バス', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (5, '003', '01', '09:08着（高速舞子08:25発）福良行', 1, '0908', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (6, '003', '02', '09:29着（三宮08:25発）福良行', 2, '0929', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (7, '003', '03', '10:06着（三宮09:00発）陸の港西淡行', 3, '1006', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (8, '003', '04', '10:29着（三宮09:25発）福良行', 4, '1029', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (9, '003', '05', '11:14着（三宮10:10発）福良行', 5, '1114', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (10, '003', '06', '11:49着（三宮10:45発）福良行', 6, '1149', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (11, '003', '07', '12:14着（三宮11:10発）福良行', 7, '1214', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (12, '003', '08', '12:38着（高速舞子11:55発）福良行', 8, '1238', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (13, '003', '09', '13:06着（三宮12:00発）陸の港西淡行', 9, '1306', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (14, '003', '10', '13:14着（三宮12:10発）福良行', 10, '1314', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (15, '003', '11', '13:38着（高速舞子12:55発）福良行', 11, '1338', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (16, '003', '12', '14:14着（三宮13:10発）福良行', 12, '1414', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (17, '003', '13', '15:06着（三宮14:00発）陸の港西淡行', 13, '1506', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (18, '003', '14', '15:14着（三宮14:10発）福良行', 14, '1514', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (19, '003', '15', '16:14着（三宮15:05発）福良行', 15, '1614', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (20, '003', '16', '16:38着（高速舞子15:55発）福良行', 16, '1638', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (21, '003', '17', '16:49着（三宮15:40発）福良行', 17, '1649', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (22, '003', '18', '17:06着（三宮16:00発）陸の港西淡行', 18, '1706', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (23, '003', '19', '17:38着（高速舞子16:55発）福良行', 19, '1738', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (24, '003', '20', '17:39着（三宮16:30発）福良行', 20, '1739', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (25, '003', '21', '18:14着（三宮17:05発）福良行', 21, '1814', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (26, '004', '01', '希望する', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (27, '004', '02', '希望しない', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (28, '005', '01', '酵素浴', 1, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (29, '005', '02', '朝からリフレッシュコース', 2, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (30, '005', '10', 'お昼からリフレッシュコース', 3, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (31, '005', '07', 'お昼からのスイーツコース', 4, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (32, '005', '08', '美肌コース', 5, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (33, '005', '09', '免疫力アップコース', 6, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (34, '005', '03', '酵素部屋１部屋貸切コース', 7, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (35, '005', '04', '断食コース（初めて）', 8, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (36, '005', '06', '断食コース（リピート）', 9, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (37, '005', '05', 'ペット酵素浴', 10, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (38, '006', '01', '男性', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (39, '006', '02', '女性', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (40, '007', '01', '0', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (41, '007', '02', '100', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (42, '008', '01', '無し', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (43, '008', '02', '有り', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (44, '009', '01', '追加しない', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (45, '009', '02', '追加する', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (46, '010', '01', '追加しない', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (47, '010', '02', '追加する', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (48, '011', '01', '無し', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (49, '011', '02', 'デラックスルーム（～2名）', 4, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (50, '011', '03', 'ツイン（１～２名）', 3, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (51, '011', '04', 'シングル（1名）', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (52, '012', '01', '1名', 1, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (53, '012', '02', '2名', 2, '2', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (54, '012', '03', '3名', 3, '3', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (55, '015', '01', '1名', 1, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (56, '015', '02', '2名', 2, '2', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (57, '015', '03', '3名', 3, '3', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (58, '015', '04', '4名', 4, '4', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (59, '015', '05', '5名', 5, '5', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (60, '015', '06', '6名', 6, '6', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (61, '016', '01', '1匹', 1, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (62, '016', '02', '2匹', 2, '2', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (63, '016', '03', '3匹', 3, '3', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (64, '017', '01', '1', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (65, '017', '02', '2', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (66, '017', '03', '3', 3, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (67, '018', '01', '1', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (68, '018', '02', '2', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (69, '018', '03', '3', 3, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (70, '018', '04', '4', 4, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (71, '019', '01', '1', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (72, '022', '01', '無し', 1, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (73, '022', '02', '有り', 2, '', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (74, '023', '01', '無し', 0, '0', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (75, '023', '02', '1名', 1, '1', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (76, '023', '03', '2名', 2, '2', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (77, '023', '04', '3名', 3, '3', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (78, '023', '05', '4名', 4, '4', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (79, '023', '06', '5名', 5, '5', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (80, '023', '07', '6名', 6, '6', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (81, '024', '01', '3390', 1, '酵素浴:  大人', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (82, '024', '02', '2800', 2, '酵素浴:  学生', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (83, '024', '03', '2000', 3, '酵素浴:  小学生', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (84, '025', '01', '8390', 1, '1 day refresh (Include lunch)', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (85, '026', '01', '20000', 1, '3', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (86, '026', '02', '3000', 2, '貸切+1人', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (87, '027', '01', '9800', 1, '断食コース 1 ngày', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (88, '027', '02', '45000', 2, '断食コース 5 ngày', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (89, '028', '01', '3500', 1, 'Pet', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (90, '029', '01', '1200', 1, 'Lunch', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (91, '029', '02', '7000', 2, '宿泊 1人 モーニング', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (92, '029', '03', '10000', 3, '宿泊 1人 > 2人 モーニング', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (93, '029', '04', '500', 4, 'pet 円 / h', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (94, '029', '05', '1000', 5, 'pet 1 day refresh', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (95, '029', '06', '3500', 6, 'Whitening 円 / h', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (96, '030', '01', '3500回', 1, '酵素浴（大人）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (97, '030', '02', '2800回', 2, '酵素浴（学生）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (98, '030', '03', '2000回', 3, '酵素浴（小学生）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (99, '030', '04', '1200名', 15, 'ランチ', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (100, '030', '05', '10000名', 4, '朝からリフレッシュコース', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (101, '030', '06', '22000回', 9, '酵素部屋１部屋貸切プラン', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (102, '030', '07', '3300名', 10, '酵素部屋１部屋貸切プラン（追加）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (103, '030', '08', '12000回', 11, '断食コース（1日コース）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (104, '030', '09', '65000回', 12, '断食コース（5日間体質改善コース ）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (105, '030', '10', '12000泊', 25, 'レンタルルーム（デラックスルーム、1名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (106, '030', '11', '12000泊', 27, 'レンタルルーム（デラックスルーム、2名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (107, '030', '12', '7700泊', 23, 'レンタルルーム（ツイン、1名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (108, '030', '13', '12000泊', 24, 'レンタルルーム（ツイン、2名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (109, '030', '14', '7700泊', 21, 'レンタルルーム（シングル、1名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (110, '030', '15', '600名', 29, 'モーニング', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (111, '030', '16', '3500回', 13, 'ペット酵素浴', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (112, '030', '17', '2500回', 14, 'ペット酵素浴（1匹追加）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (113, '030', '18', '500回', 19, 'ペット預かり（酵素浴1回）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (114, '030', '19', '1000回', 20, 'ペット預かり（リフレッシュプラン）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (115, '030', '20', '3500回', 16, 'ニュースキャン', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (116, '030', '21', '10000名', 6, 'お昼からのスイーツコース', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (117, '030', '22', '8500名', 7, '美肌コース', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (118, '030', '23', '7500名', 8, '免疫力アップコース', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (119, '013', '01', '09:45', 1, '0945', '0945');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (120, '013', '02', '10:15', 2, '1015', '1015');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (121, '013', '03', '10:45', 3, '1045', '1045');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (122, '013', '04', '13:15', 4, '1315', '1315');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (123, '013', '05', '13:45', 5, '1345', '1345');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (124, '013', '06', '14:15', 6, '1415', '1415');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (125, '013', '07', '15:15', 7, '1515', '1515');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (126, '013', '08', '15:45', 8, '1545', '1545');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (127, '013', '09', '16:15', 9, '1615', '1615');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (128, '013', '10', '17:45', 10, '1745', '1745');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (129, '013', '11', '18:15', 11, '1815', '1815');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (130, '014', '01', '09:45', 1, '0945', '0945');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (131, '014', '02', '13:15', 2, '1315', '1315');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (132, '014', '03', '15:15', 3, '1515', '1515');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (133, '020', '01', '09:30～10:30', 1, '0930-1030', '0930');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (134, '020', '02', '11:00～12:00', 2, '1100-1200', '1100');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (135, '020', '03', '14:00～15:00', 3, '1400-1500', '1400');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (136, '020', '04', '15:30～16:30', 4, '1530-1630', '1530');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (137, '021', '01', '09:30～10:00', 1, '0930-1000|1', '0930');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (138, '021', '02', '10:30～11:00', 2, '1030-1100|0', '1030');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (139, '021', '03', '11:00～11:30', 3, '1100-1130|1', '1100');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (140, '021', '04', '12:00～12:30', 4, '1200-1230|0', '1200');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (141, '021', '05', '12:30～13:00', 5, '1230-1300|0', '1230');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (142, '021', '06', '13:00～13:30', 6, '1300-1330|1', '1300');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (143, '021', '07', '14:00～14:30', 7, '1400-1430|0', '1400');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (144, '021', '08', '14:30～15:00', 8, '1430-1500|0', '1430');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (145, '021', '09', '15:00～15:30', 9, '1500-1530|1', '1500');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (146, '021', '10', '16:00～16:30', 10, '1600-1630|0', '1600');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (147, '021', '11', '16:30～17:00', 11, '1630-1700|1', '1630');
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (148, '030', '24', '10000名', 5, 'お昼からリフレッシュコース', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (149, '030', '25', '11000泊', 26, 'レンタルルーム（デラックスルーム、1名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (150, '030', '26', '11000泊', 28, 'レンタルルーム（デラックスルーム、2名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (151, '030', '27', '7000泊', 22, 'レンタルルーム（シングル、1名）', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (152, '030', '28', '3500回', 17, 'ホワイトニング', NULL);
INSERT INTO ms_kubun (ms_kubun_id, kubun_type, kubun_id, kubun_value, sort_no, notes, time_holiday) VALUES (153, '030', '29', '5000回', 18, 'コアチューニング', NULL);

ALTER TABLE tr_yoyaku ADD COLUMN tea tinyint(4) DEFAULT '0';

ALTER TABLE tr_yoyaku
ADD COLUMN whitening2 varchar(2) DEFAULT NULL;

ALTER TABLE tr_yoyaku
ADD COLUMN whitening_repeat2 varchar(1) DEFAULT NULL;

ALTER TABLE tr_yoyaku
ADD COLUMN core_tuning varchar(2) DEFAULT NULL;